### ISSUE TITLE
Broken bootstrap using current Apraxis

### ISSUE THREAD

**Issue by michaelparenteau** [apraxis/pixels-against-humanity#2]
@aredington I tried doing a fresh bootstrap of PAH with the last couple commits in Apraxis. http://localhost:8080/dev/components/card and http://localhost:8080/dev/components/test both load.. but http://localhost:8080/dev/components/prompt-and-answers and http://localhost:8080/dev/components/prompt-and-answers-scroll component test pages don't render anything other than the template html file the Cljs fies depend on... so no sample data magick. When going back to commit `416db87c11d54de0e2eebc8d136ffcb22b02841d` and doing a `lein install` again in /apraxis.. everything works again. What do I need to do to make these things work again?

**Comment by aredington** [comment]
Fixed in https://github.com/apraxis/apraxis/commit/a05b45cea2c19135c834cbf9c1c96ca44e12fe56

**Comment by samumbach** [comment]
Thanks @aredington !!!
